sonar.projectKey=glair-vision-java
sonar.projectName=glair-vision-java
sonar.projectVersion=0.0.1

sonar.sourceEncoding=UTF-8
sonar.sources=vision/src/main/java
sonar.tests=vision/src/test/java
sonar.test.inclusions=**/*Test.java

sonar.java.binaries=vision/build/classes/java/main
sonar.java.libraries=vision/build/libs/*.jar

sonar.coverage.jacoco.xmlReportPaths=vision/build/reports/jacoco/test/jacocoTestReport.xml
sonar.language=java
